version: "3.9"
services:
    guess-my-number:
        build:
            dockerfile: Dockerfile.dev
            context: ./
        ports:
            - "4200:4200"
        volumes:
            - ./:/opt/src/app

    sonarqube-server:
        image: sonarqube:lts-community
        depends_on:
            - sonarqube-db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_extensions:/opt/sonarqube/extensions
        ports:
            - "9000:9000"

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000"]
            timeout: 5m
    sonarqube-db:
        image: postgres:12
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data

    sonarqube-scanner:
        image: sonarsource/sonar-scanner-cli
        depends_on:
            - sonarqube-server
        volumes:
            - ./:/usr/src
        command:
            [
                "./wait-for-sonarqube.sh",
                "sonarqube-server:9000",
                "sonar-scanner",
            ]

volumes:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions:
    postgresql:
    postgresql_data:
