version: "3.9"
services:
    guess-my-number:
        image: jitpz/guess-my-number
        ports:
            - "80:80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
